name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install Root Dependencies
      run: npm install

    - name: Install Client & Server Dependencies
      run: |
        cd server && npm install
        cd ../client && npm install

    - name: Build Frontend Application
      run: |
        cd client && npm run build
